version: '3.4'

services:

  roh-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: rohdb
      MYSQL_USER: roh
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: rootdocker
    ports:
      - 3306:3306
    volumes:
      - rohdb_data

volumes:
  rohdb_data:
    name: "rohdb"